# Generated by Django 6.0 on 2026-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('cart', 'Cart'), ('single', 'Single Product')], default='cart', max_length=10),
        ),
    ]
